 version: '2'

services:
  wetty:
    build: .
    image: kgustafs/wetty
    container_name: wetty
    environment:
      - REMOTE_SSH_SERVER=ssh.example.com
      - REMOTE_SSH_PORT=22
      - REMOTE_SSH_USER=root
    ports:
      - 3100:3000
    restart: unless-stopped
    logging:
      options:
        max-size: 10m